### ISSUE TITLE
On Windows Install

### ISSUE THREAD

**Issue by Defragster** [ftrias/TeensyDebug#1]
GDB is :: "T:\arduino-1.8.12\hardware\tools\arm\bin\arm-none-eabi-gdb.exe"

Com port ( as found by TyComm ) given as :: (gdb) target remote \\.\com21

>> not yet done reading the README - but those are the first two notes for WINDOWS 10

**Comment by ftrias** [comment]
Closing as stale. Please reopen with more details if this is still a problem.
