### ISSUE TITLE
Compiler warnings redefined O_CREAT and O_APPEND

### ISSUE THREAD

**Issue by MVogtDD** [ftrias/TeensyDebug#20]
This is a benign, however easy to fix issue yielding compiler warnings for redefinitions of O_CREAT and O_APPEND in TeensyDebug.h which conflicts definitions in arm-none-eabi\include\sys\fcntl.h

The exact definitions there are
#define	_FCREAT		0x0200	/* open with file create */
#define	O_CREAT		_FCREAT
#define	_FAPPEND	0x0008	/* append (writes guaranteed at the end) */
#define	O_CREAT		_FCREAT

**Comment by MVogtDD** [comment]
Just seen this isue has already been handled in
https://github.com/h4yn0nnym0u5e/TeensyDebug/archive/refs/heads/feature/fixes-01.zip

**Comment by ftrias** [comment]
Thanks for the heads up. I just merged the change.
